version: '3.9'
services:
  backend:
    build: .
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
    - db
  db:
    image: library/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: akarak
      MYSQL_ROOT_USER : root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
    - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
#  redis:
#    image: redis
#    ports:
#    - 6379:6379
